# Generated by Django 5.1.2 on 2024-11-16 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("absent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="absent",
            options={"ordering": ["-create_time"]},
        ),
    ]
